[package]
name = "rust-keylime-pull-model"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.80", features = ["derive"] }
serde_derive = "1.0.80"
serde_json = { version = "1.0", features = ["raw_value"] }
