openapi: 3.0.0
info:
  title: Capabilities Negotiation API
  version: 1.0.0
components:
  schemas:
    AttestationRequest: # Request schema
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
              example: attestation
            attributes:
              type: object
              properties:
                evidence_supported:
                  type: array
                  items:
                    type: object
                    properties:
                      evidence_class:
                        type: string
                        example: certification
                      evidence_type:
                        type: string
                        example: tpm_quote
                      agent_capabilities:
                        type: object
                        properties:
                          spec_version:
                            type: string
                            example: "2.0"
                          hash_algorithms:
                            type: array
                            items:
                              type: string
                              example: sha3_512
                          signing_schemes:
                            type: array
                            items:
                              type: string
                              example: rsassa
                          attestation_keys:
                            type: array
                            items:
                              type: object
                              properties:
                                key_class:
                                  type: string
                                  example: private_key
                                key_identifier:
                                  type: string
                                  example: "attestation_key_identifier"
                                key_algorithm:
                                  type: string
                                  example: rsa
                                public_hash:
                                  type: string
                                  example: "cd293be6cea034bd45a0352775a219ef5dc7825ce55d1f7dae9762d80ce64411"
                        required:
                          - spec_version
                          - hash_algorithms
                          - signing_schemes
                          - attestation_keys
                      version:  # Only present for some evidence types
                        type: string
                        example: "2.1"
                boot_time:
                  type: string
                  format: date-time
                  example: "2024-11-12T16:21:17Z"
              required:
                - evidence_supported
                - boot_time
          required:
            - type
            - attributes
      required:
        - data
    AttestationResponse: # Response schema
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
              example: attestation
            attributes:
              type: object
              properties:
                evidence_collected: # Nuevo campo para la respuesta
                  type: array
                  items:
                    type: object
                    properties:
                      evidence_class:
                        type: string
                        example: certification
                      evidence_type:
                        type: string
                        example: tpm_quote
                      chosen_parameters:
                        type: object
                        properties:
                          nonce:
                            type: string
                            example: "here_the_nonce"
                          pcr_selection:
                            type: array
                            items:
                              type: integer
                              example: 0
                          hash_algorithm:
                            type: string
                            example: sha384
                          signing_scheme:
                            type: string
                            example: rsassa
                          attestation_key:
                            type: object
                            properties:
                              key_class:
                                type: string
                                example: private_key
                              key_identifier:
                                type: string
                                example: "attestation_key_identifier"
                              key_algorithm:
                                type: string
                                example: rsa
                              public_hash:
                                type: string
                                example: "cd293be6cea034bd45a0352775a219ef5dc7825ce55d1f7dae9762d80ce64411"
                          starting_offset: # Only for some evidence types
                            type: integer
                            example: 25
                boot_time:
                  type: string
                  format: date-time
                  example: "2024-11-12T16:21:17Z"
              required:
                - evidence_collected
                - boot_time
          required:
            - type
            - attributes
      required:
        - data
paths:
  /agents/{id}/attestations:
    post:
      summary: Create Attestation Data for Agent
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the agent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AttestationRequest' # Usa AttestationRequest
      responses:
        '201':
          description: Attestation data created successfully
        '200':
          description: Attestation data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttestationResponse' # Usa AttestationResponse
        '400':
          description: Bad request (e.g., invalid input)
        # other possible response codes